---
title: "Avaliação parcial da Área 2"
author: |
  | \textsc{Universidade Federal do Rio Grande do Sul}
  | \textsc{Instituto de Matemática e Estatística}
  | \textsc{Departamento de Estatística}
  | \textsc{MAT02035 - Modelos para dados correlacionados}
  |
  | Rodrigo Citton P. dos Reis
  | `citton.padilha@ufrgs.br`
output:
  pdf_document: default
  html_document: default
  word_document: default
---

__Questão 1 (1 ponto)__ Apresente as principais características de um estudo longitudinal.

__Questão 2 (1 ponto)__ Para um estudo longitudinal, descreva as diferenças entre os delineamentos balanceado e desbalanceado.

__Questão 3 (2 pontos)__ No estudo TLC (_estudo sobre tratamento de crianças
expostas ao chumbo_), considere somente as duas primeiras medidas do estudo: linha de base (semana 0) e semana 1. Suponha que é de interesse determinar se existe uma mudança na resposta média ao longo do tempo. Uma estimativa da mudança na reposta média é dada por $\hat{\delta} = \hat{\mu}_2 - \hat{\mu}_1$, em que $\hat{\mu}_j = \frac{1}{N}\sum_{i=1}^N{Y_{ij}},\ j = 1, 2$. A expressão da variância de $\hat{\delta}$ é dada por 

$$
\mbox{Var}(\hat{\delta}) = \mbox{Var}\left\{ \frac{1}{N}\sum_{i=1}^N{(Y_{i2} - Y_{i1})}\right\} = \frac{1}{N}(\sigma^2_1 + \sigma^2_2 - {\color{purple}{2\sigma_{12}}}).
$$

Note que a expressão acima inclui o termo $-2\sigma_{12}$. Este termo é o responsável por levar em consideração a correlação entre as duas primeiras medidas repetidas. Para os dados do estudo, no grupo __succimer__ ($N = 50$), temos $\hat{\delta} = 13.5 - 26.5 = - 13, \hat{\sigma}^2_1 = 25.2, \hat{\sigma}^2_2 = 58.9$ e $\hat{\sigma}_{12} = 15.5$.

1. Com os dados apresentados acima, calcule $\widehat{\mbox{Var}}(\hat{\delta})$. Logo em seguida, calcule $\widehat{\mbox{Var}}(\hat{\delta})$, mas agora assumindo que todas as observações são independentes.
2. Utilize os resultados do item anterior e discuta as consequências de se ignorar a correlação entre os dados de medidas repetidas.

__Questão 4 (3 pontos)__ Mais uma vez, considere o estudo TLC, um estudo aleatorizado, controlado por placebo, de um agente quelante administrado por via oral, o _succimer_, em crianças com níveis confirmados de chumbo no sangue de 20 a 44 $\mu$g/dL. As crianças do estudo tinham idades entre 12 e 33 meses e viviam em moradias deterioradas no centro da cidade. Dados sobre os níveis de chumbo no sangue na linha de base (semana 0), e nas semanas 1, 4 e 6 do primeiro período de tratamento foram coletados. Na figura abaixo é apresentado o gráfico de médias de repostas por grupos de tratamento em cada ocasião de medição.

```{r tlc_p, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE, fig.align='center', out.width="50%"}
# ----------------------------------------------------
# Carregando pacotes do R

library(here)
library(haven)
library(tidyr)
library(ggplot2)

# ----------------------------------------------------
# Carregando o arquivo de dados

chumbo.df <- read_dta(file = here::here("data", "tlc.dta"))

chumbo.df$trt <- factor(chumbo.df$trt, labels = c("Placebo", "Succimer"))

# ----------------------------------------------------
# Reformando o objeto: de "largo" para "longo"

chumbo.df.longo <- gather(data = chumbo.df, key = "tempo", value = "chumbo", -id, -trt)

# ----------------------------------------------------
# Formata variáveis

chumbo.df.longo$tempo <- factor(chumbo.df.longo$tempo, labels = c("0", "1", "4", "6"))
chumbo.df.longo$tempo.num <- as.numeric(as.character(chumbo.df.longo$tempo))

# ----------------------------------------------------

library(plyr)

chumbo.resumo <- ddply(chumbo.df.longo, ~ trt + tempo.num, summarize, chumbo.m = mean(chumbo))

p <- ggplot(data = chumbo.resumo,
            mapping = aes(x = tempo.num, y = chumbo.m, group = trt, colour = trt)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = c(0, 1, 4, 6)) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "Tempo (em semanas)",
       y = expression("Média nível de chumbo no sangue"~(mu*g/dL)),
       colour = "Grupo de tratamento") +
  theme_bw() +
  theme(legend.position = "bottom")
p
```

1. Sugira um modelo de regressão para a resposta média. Justifique a sua escolha. Como você classifica a abordagem do modelo escolhido: perfis de resposta ou curvas paramétricas?
2. Com base no modelo que você propôs no item anterior, apresente a matriz de delineamento $X_i$ para um indivíduo do grupo _succimer_ e para um indivíduo do grupo placebo.
3. Com base no modelo que você propôs, apresente uma hipótese estatística para testar se o padrão de mudanças ao longo do tempo difere entre os grupos. Além disso, descreva o teste (Wald, Razão de Verossimilhanças, ou outro) e a distribuição de referência.

__Questão 5 (3 pontos)__ Considere o estudo de crescimento dentário, as medidas da distância (mm) do centro da glândula pituitária à fissura pteromaxilar foram obtidas em 11 meninas e 16 meninos nas idades de 8, 10, 12 e 14 (Potthoff e Roy, 1964). Um modelo saturado (considerando efeitos de tempo, grupo [gênero], e interações $tempo \times grupo$) foi assumido para a resposta média, e os seguintes modelos para a covariância foram ajustados: (`mod.ne`) covariância não estruturada;  (`mod.sc`) simetria composta; (`mod.ar`) autorregressiva.

1. Para este estudo acima, descreva $N$, o número de indivíduos, $n$, o número de medidas repetidas, e $t_{ij}$.
2. Para cada um dos modelos de covariância, escreva a matriz $\mbox{Cov}(Y_i)$, em que $Y_i$ representa o vetor de respostas.
3. Com base nas comparações abaixo ($gl$ representa os graus de liberdade, AIC é o Critério de Informação de Akaike, logVero é a log-verossimilhança maximizada, RV é a razão de verossimilhança), escolha um modelo de covariância se ajuste adequadamente aos dados. Justifique a sua resposta.

|       | Modelo| $gl$|      AIC|    logVero|Teste   |  RV|   Valor $p$|
|:------|-----:|--:|--------:|---------:|:------|--------:|--------:|
|`mod.ne` |     1| 18| 450.0348| -207.0174|       |       |       |
|`mod.ar` |     2| 10| 454.5472| -217.2736|1 vs 2 | 20.51237| 0.0086|

\

|       | Modelo| $gl$|      AIC|    logVero|Teste   |  RV|   Valor $p$|
|:------|-----:|--:|--------:|---------:|:------|--------:|---------:|
|`mod.ne` |     1| 18| 450.0348| -207.0174|       |       |        |
|`mod.sc` |     2| 10| 443.4085| -211.7043|1 vs 2 | 9.373732| 0.3118|

\

|       | Modelo| $gl$|      AIC|    logVero|
|:------|-----:|--:|--------:|---------:|
|`mod.sc` |     1| 10| 443.4085| -211.7043|
|`mod.ar` |     2| 10| 454.5472| -217.2736|
