---
title: "Avaliação parcial da Área 1"
subtitle: "Resolução"
author: |
  | \textsc{Universidade Federal do Rio Grande do Sul}
  | \textsc{Instituto de Matemática e Estatística}
  | \textsc{Departamento de Estatística}
  | \textsc{MAT02035 - Modelos para dados correlacionados}
  |
  | Rodrigo Citton P. dos Reis
  | `citton.padilha@ufrgs.br`
output:
  pdf_document: default
  html_document: default
  word_document: default
---

__Questão 1 (1 ponto)__ Apresente as principais características de um estudo longitudinal.
\

\color{blue}

- A característica definidora de estudos longitudinais é que medidas dos mesmos indivíduos são tomadas repetidamente através do tempo, permitindo, assim, o estudo direto da mudança ao longo do tempo. Uma característica distintiva de dados longitudinais é que eles são agrupados. Ou seja, cada indivíduo forma um grupo de observações repetidas ao longo do tempo. Dados longitudinais também possuem um ordenamento temporal, e este tem implicações importantes para a análise. Observações dentro de um grupo tipicamente irão exibir correlação positiva, e esta correlação deve ser levada em conta na análise.
\

\color{black}

__Questão 2 (1 ponto)__ Para um estudo longitudinal, descreva as diferenças entre os delineamentos balanceado e desbalanceado.
\

\color{blue}

- Se o número e o momento das medições repetidas são os mesmos para todos os indivíduos, independentemente das ocasiões de medição serem igualmente ou
desigualmente distribuídas ao longo da duração do estudo, diremos que o estudo é balanceado. Quando a sequência dos tempos de observação não é mais comum a todos os indivíduos no estudo, diremos que o estudo é desbalanceado.
\

\color{black}

__Questão 3 (2 pontos)__ No estudo TLC (_estudo sobre tratamento de crianças
expostas ao chumbo_), considere somente as duas primeiras medidas do estudo: linha de base (semana 0) e semana 1. Suponha que é de interesse determinar se existe uma mudança na resposta média ao longo do tempo. Uma estimativa da mudança na reposta média é dada por $\hat{\delta} = \hat{\mu}_2 - \hat{\mu}_1$, em que $\hat{\mu}_j = \frac{1}{N}\sum_{i=1}^N{Y_{ij}},\ j = 1, 2$. A expressão da variância de $\hat{\delta}$ é dada por 

$$
\mbox{Var}(\hat{\delta}) = \mbox{Var}\left\{ \frac{1}{N}\sum_{i=1}^N{(Y_{i2} - Y_{i1})}\right\} = \frac{1}{N}(\sigma^2_1 + \sigma^2_2 - {\color{purple}{2\sigma_{12}}}).
$$

Note que a expressão acima inclui o termo $-2\sigma_{12}$. Este termo é o responsável por levar em consideração a correlação entre as duas primeiras medidas repetidas. Para os dados do estudo, no grupo __succimer__ ($N = 50$), temos $\hat{\delta} = 13.5 - 26.5 = - 13, \hat{\sigma}^2_1 = 25.2, \hat{\sigma}^2_2 = 58.9$ e $\hat{\sigma}_{12} = 15.5$.

1. Com os dados apresentados acima, calcule $\widehat{\mbox{Var}}(\hat{\delta})$. Logo em seguida, calcule $\widehat{\mbox{Var}}(\hat{\delta})$, mas agora assumindo que todas as observações são independentes.
\

\color{blue}

$$
\widehat{\mbox{Var}}(\hat{\delta}) = \frac{1}{50}(25.2 + 58.9 - 2(15.5)) = 1.06.
$$

Se ignorássemos o fato que os dados são correlacionados e e procedêssemos com uma análise assumindo que todas as observações são independentes (e portanto, não correlacionados, com covariância zero), teríamos a seguinte estimativa __(incorreta)__ da variância da mudança na resposta média

$$
\frac{1}{50}(25.2 + 58.9) = 1.68.
$$
\

\color{black}

2. Utilize os resultados do item anterior e discuta as consequências de se ignorar a correlação entre os dados de medidas repetidas.
\

\color{blue}

- Ao ignorar a correlação entre os dados, obtemos uma estimativa da variância da mudança na resposta média $1.6$ vezes maior que a estimativa correta. Isso acarretará em: erros padrões muito grandes (superestimados); intervalos de confiança muito largos; valores $p$ para o teste $H_0: \delta = 0$ muito grandes. Em resumo, não levar em conta a correlação entre as medidas repetidas irá, em geral, resultar em estimativas incorretas da variabilidade amostral, que levam a inferências bastante enganosas.
\

\color{black}

__Questão 4 (3 pontos)__ Mais uma vez, considere o estudo TLC, um estudo aleatorizado, controlado por placebo, de um agente quelante administrado por via oral, o _succimer_, em crianças com níveis confirmados de chumbo no sangue de 20 a 44 $\mu$g/dL. As crianças do estudo tinham idades entre 12 e 33 meses e viviam em moradias deterioradas no centro da cidade. Dados sobre os níveis de chumbo no sangue na linha de base (semana 0), e nas semanas 1, 4 e 6 do primeiro período de tratamento foram coletados. Na figura abaixo é apresentado o gráfico de médias de repostas por grupos de tratamento em cada ocasião de medição.

```{r tlc_p, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE, fig.align='center', out.width="50%"}
# ----------------------------------------------------
# Carregando pacotes do R

library(here)
library(haven)
library(tidyr)
library(ggplot2)

# ----------------------------------------------------
# Carregando o arquivo de dados

chumbo.df <- read_dta(file = here::here("data", "tlc.dta"))

chumbo.df$trt <- factor(chumbo.df$trt, labels = c("Placebo", "Succimer"))

# ----------------------------------------------------
# Reformando o objeto: de "largo" para "longo"

chumbo.df.longo <- gather(data = chumbo.df, key = "tempo", value = "chumbo", -id, -trt)

# ----------------------------------------------------
# Formata variáveis

chumbo.df.longo$tempo <- factor(chumbo.df.longo$tempo, labels = c("0", "1", "4", "6"))
chumbo.df.longo$tempo.num <- as.numeric(as.character(chumbo.df.longo$tempo))

# ----------------------------------------------------

library(plyr)

chumbo.resumo <- ddply(chumbo.df.longo, ~ trt + tempo.num, summarize, chumbo.m = mean(chumbo))

p <- ggplot(data = chumbo.resumo,
            mapping = aes(x = tempo.num, y = chumbo.m, group = trt, colour = trt)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = c(0, 1, 4, 6)) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "Tempo (em semanas)",
       y = expression("Média nível de chumbo no sangue"~(mu*g/dL)),
       colour = "Grupo de tratamento") +
  theme_bw() +
  theme(legend.position = "bottom")
p
```

1. Sugira um modelo de regressão para a resposta média. Justifique a sua escolha. Como você classifica a abordagem do modelo escolhido: perfis de resposta ou curvas paramétricas?
\

__(A resolução permite diferentes respostas. Aqui é apresentada uma destas respostas.)__

\color{blue}
\

- Observe que, a partir do gráfico das médias, nos parece que apenas os níveis médios de chumbo no sangue no grupo placebo podem ser descritos por uma tendência linear; a média no grupo _succimer_ diminui da linha de base até a semana 1, mas depois aumenta. Uma forma de acomodarmos tendências não lineares no modelo de regressão linear geral é por meio de tendências lineares por partes, neste caso, com inclusão de nó comum aos dois grupos de tratamento na semana 1 ($t^{*} = 1$),

\begin{eqnarray*}
\mbox{E}(Y_{ij}) &=& \beta_1 + \beta_2 Semana_{ij} + \beta_3 (Semana_{ij} - 1)_{+}\\
&& + \beta_4 (Semana_{ij} \times Grupo_i) + \beta_5 \{(Semana_{ij} - 1)_{+} \times Grupo_i\},\\
&&\ i = 1, \ldots, 100,\ j = 1, 2, 3, 4, 
\end{eqnarray*}
em que $Grupo_i = 1$ se o $i$-ésimo indivíduo foi designado ao novo tratamento, e $Grupo_i = 0$ caso contrário. A ausência de um efeito de grupo se justifica por se tratar de um estudo experimental aleatorizado, em que os indivíduos apresentam um comportamento semelhante na linha de base. O termo de interação permite capturar diferentes tendências para os dois grupos. A abordagem sugerida é a de curvas paramétricas.
\

\color{black}

2. Com base no modelo que você propôs no item anterior, apresente a matriz de delineamento $X_i$ para um indivíduo do grupo _succimer_ e para um indivíduo do grupo placebo.
\

__(A resolução permite diferentes respostas. Aqui é apresentada uma destas respostas, com base no item anterior.)__

\color{blue}

- Para o grupo _succimer_, temos:

$$
X_i = \left(\begin{array}{ccccc}
1 & 0 & (0 - 1)_{+} & 0 & (0 - 1)_{+} \\
1 & 1 & (1 - 1)_{+} & 1 & (1 - 1)_{+} \\
1 & 4 & (4 - 1)_{+} & 4 & (4 - 1)_{+} \\
1 & 6 & (6 - 1)_{+} & 6 & (6 - 1)_{+} \\
\end{array}
\right) = 
\left(\begin{array}{ccccc}
1 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 1 & 0 \\
1 & 4 & 3 & 4 & 3 \\
1 & 6 & 5 & 6 & 5 \\
\end{array}
\right).
$$
- Para o grupo placebo, temos:

$$
X_i = \left(\begin{array}{ccccc}
1 & 0 & (0 - 1)_{+} & 0 & 0 \\
1 & 1 & (1 - 1)_{+} & 0 & 0 \\
1 & 4 & (4 - 1)_{+} & 0 & 0 \\
1 & 6 & (6 - 1)_{+} & 0 & 0 \\
\end{array}
\right) = 
\left(\begin{array}{ccccc}
1 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 0 \\
1 & 4 & 3 & 0 & 0 \\
1 & 6 & 5 & 0 & 0 \\
\end{array}
\right).
$$
\

\color{black}

3. Com base no modelo que você propôs, apresente uma hipótese estatística para testar se o padrão de mudanças ao longo do tempo difere entre os grupos. Além disso, descreva o teste (Wald, Razão de Verossimilhanças, ou outro) e a distribuição de referência.
\

__(A resolução permite diferentes respostas. Aqui é apresentada uma destas respostas, com base nos ítens anteriores.)__

\color{blue}

- Para testar se o padrão de mudanças ao longo do tempo difere entre os grupos, podemos testar a hipótese de ausência de efeito de intereção

$$
H_0: \beta_4 = \beta_5 = 0.
$$
Note que podemos reescrever a hipótese nula como $H_0: L\beta = 0$, em que $\beta = (\beta_1, \ldots, \beta_5)'$ é o vetor de coeficientes de regressão e

$$
L = \left(\begin{array}{ccccc}
0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 \\
\end{array}
\right).
$$

O teste

$$
W^2 = (L\hat{\beta})'\{L\widehat{\mbox{Cov}}(\hat{\beta})L'\}^{-1}(L\hat{\beta}),
$$

que tem uma distribuição qui-quadrado com $2$ graus de liberdade ($\chi^2_{(2)}$) pode ser usado para avaliar $H_0: L\beta = 0$ versus $H_A: L\beta \neq 0$.
\

\color{black}

__Questão 5 (3 pontos)__ Considere o estudo de crescimento dentário, as medidas da distância (mm) do centro da glândula pituitária à fissura pteromaxilar foram obtidas em 11 meninas e 16 meninos nas idades de 8, 10, 12 e 14 (Potthoff e Roy, 1964). Um modelo saturado (considerando efeitos de tempo, grupo [gênero], e interações $tempo \times grupo$) foi assumido para a resposta média, e os seguintes modelos para a covariância foram ajustados: (`mod.ne`) covariância não estruturada;  (`mod.sc`) simetria composta; (`mod.ar`) autorregressiva.

1. Para este estudo acima, descreva $N$, o número de indivíduos, $n$, o número de medidas repetidas, e $t_{ij}$.
\

\color{blue}

- $N = 11 + 16 = 27;\ n = 4;\ t_{ij} = t_j$, em que $t_1 = 8,\ t_2 = 10,\ t_3 = 12,\ t_4 =14$.
\

\color{black}

2. Para cada um dos modelos de covariância, escreva a matriz $\mbox{Cov}(Y_i)$, em que $Y_i$ representa o vetor de respostas.
\

\color{blue}

__Matriz de covariância não estruturada__

$$
\mbox{Cov}(Y_i) = \left(\begin{array}{cccc}
\sigma^2_1 & \sigma_{12} & \sigma_{13} & \sigma_{14} \\
\sigma_{21} & \sigma^2_2 & \sigma^2_{23} & \sigma_{24} \\
\sigma_{31} & \sigma_{32} & \sigma_3 & \sigma_{34} \\
\sigma_{41} & \sigma_{42} & \sigma_{43} & \sigma^2_4 \\
\end{array}
\right),
$$
em que $\sigma^2_j = \mbox{Var}(Y_{ij}),\ j = 1,\ldots, 4$ e $\sigma_{kj} = \sigma_{jk} = \mbox{Cov}(Y_{ij}, Y_{ik}),\ j, k = 1, \ldots, 4,\ j \neq k$.

__Matriz de covariância simetria composta__

$$
\mbox{Cov}(Y_i) = \sigma^2\left(\begin{array}{cccc}
1 & \rho  & \rho & \rho \\
\rho & 1  & \rho & \rho \\
\rho & \rho & 1 &  \rho \\
\rho & \rho & \rho  & 1
\end{array}\right),
$$
em que $\rho = \mbox{Corr}(Y_{ij}, Y_{ik}),\ j, k = 1, \ldots, 4$. Note que no padrão de simetria composta é assumido que a variância e a correlação entre as medidas são constantes ao longo dos tempos de medição.

__Matriz de covariância autoregressiva__

$$
\mbox{Cov}(Y_i) = \sigma^2\left(\begin{array}{cccc}
1 & \rho  & \rho^2 & \rho^3 \\
\rho & 1  & \rho & \rho^2 \\
\rho^2 & \rho & 1 &  \rho \\
\rho^3 & \rho^2 & \rho  & 1
\end{array}\right),
$$
em que $\rho^k = \mbox{Corr}(Y_{ij}, Y_{i,j + k}),\ j, k = 1, \ldots, 4$. Note que no padrão autorregressivo é assumido que a variância é constante ao longo dos tempos de medição e que a correlação entre as medidas decai em função do espaçamento entre as medições.
\

\color{black}

3. Com base nas comparações abaixo ($gl$ representa os graus de liberdade, AIC é o Critério de Informação de Akaike, logVero é a log-verossimilhança maximizada, RV é a razão de verossimilhança), escolha um modelo de covariância se ajuste adequadamente aos dados. Justifique a sua resposta.

|       | Modelo| $gl$|      AIC|    logVero|Teste   |  RV|   Valor $p$|
|:------|-----:|--:|--------:|---------:|:------|--------:|--------:|
|`mod.ne` |     1| 18| 450.0348| -207.0174|       |       |       |
|`mod.ar` |     2| 10| 454.5472| -217.2736|1 vs 2 | 20.51237| 0.0086|

\

|       | Modelo| $gl$|      AIC|    logVero|Teste   |  RV|   Valor $p$|
|:------|-----:|--:|--------:|---------:|:------|--------:|---------:|
|`mod.ne` |     1| 18| 450.0348| -207.0174|       |       |        |
|`mod.sc` |     2| 10| 443.4085| -211.7043|1 vs 2 | 9.373732| 0.3118|

\

|       | Modelo| $gl$|      AIC|    logVero|
|:------|-----:|--:|--------:|---------:|
|`mod.sc` |     1| 10| 443.4085| -211.7043|
|`mod.ar` |     2| 10| 454.5472| -217.2736|
\

\color{blue}

- Com base no teste da razão de verossimilhanças, há evidências de que o modelo autorregressivo não fornece um ajuste adequado para a covariância, quando comparado à covariância não estruturada ($p = 0.0086$). Por outro lado, o teste da razão de verossimilhanças, comparando a covariância simetria composta e não estruturada, resulta em $G^2 = 9.374$ e $p = 0.3118$. Assim, a covariância simetria composta fornece um ajuste adequado aos dados. Por fim, vemos que o modelo de covariância simetria composta apresenta menor AIC na comparação com o modelo de covariância autorregressiva. Portanto, entre os três modelos ajustados, a covariância simetria composta apresenta ajuste mais adequado aos dados.
